### ISSUE TITLE
안녕하세요 특정 회사 연결 재무제표 안되는 문제가 있습니다.

### ISSUE THREAD

**Issue by primemacpie** [josw123/dart-scraper#20]
DOWNLOAD: [00138729]아세아제지 : ('cannot set a row with mismatched columns', "An error occurred while fetching or analyzing {'rcp_no': '20190329003134', 'corp_code': '00138729', 'corp_name': '아세아제지', 'stock_code': '002310', 'corp_cls': 'Y', 'report_nm': '사업보고서 (2018.12)', 'flr_nm': '아세아제지', 'rcept_dt': '20190329', 'rm': '연'}.")

안녕하세요 만들어주신 프로그램 잘 사용하고 있습니다.
아세아제지 연결 재무제표 분기별로 다운 받으려고 했으나 위와같은 오류가 생기면서 안됩니다.
개별은 가능합니다.
답변주시면 감사하겠습니다.

**Comment by josw123** [comment]
안녕하세요.

올려주신 오류를 확인해 보니, 아시아제지에서 2019년 03월 29일에 공시한 사업보고서 내부에 첨부된 XBRL 파일에 일부 중복된 이름이 사용되어 생긴 문제입니다.

재무제표를 Pandas DataFrame으로 변환하는 과정에서 아래와 같이 일부 컬럼의 이름이 중복되는 문제로 인하여 발생하는 오류 입니다.

```
('20181231', ('연결재무제표', '주식발행초과금'))

('20171231', ('연결재무제표', '주식발행초과금'))

('20161231', ('연결재무제표', '주식발행초과금'))
```

영문 컬럼명은 중복되지 않았으나 한글 컬럼명이 중복되어 생기는 문제로 생각되며 해당 문제는 [dart-fss](https://github.com/josw123/dart-fss) 라이브러리 업데이트를 통해 해결하도록 하겠습니다. 

이후 dart-scraper 또한 업데이트 하도록하겠습니다.

**Comment by primemacpie** [comment]
답변 감사합니다! 좋은 프로그램 만들어주셔서 감사합니다!
